spring:
  application:
    name: course

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.115.60.46:3306/micro-service1?useUnide=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      max-lifetime: 30000
      minimum-idle: 1
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 10000
      connection-timeout: 30000

#mp配置
mybatis:
  type-aliases-package: com.soft1851.server.study.entity

server:
  port: 8080

#服务注册
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:9595/eureka/

info:
  app:
    name: course
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true  #启用接口关闭 Spring Boot